name: Test rosbag2
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.1
      with:
        package-name: |
          ros2bag_future
          rosbag2_compression_future
          rosbag2_cpp_future
          rosbag2_storage_future
          rosbag2_storage_default_plugins_future
          rosbag2_transport_future
          shared_queues_vendor_future
          sqlite3_vendor_future
          rosbag2_test_common_future
          rosbag2_tests_future
        target-ros2-distro: foxy
        vcs-repo-file-url: ""
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
